#!/bin/sh

# defaults
setdisps
xset r rate 250 30
setxkbmap -option caps:escape pl

# accel etc
xinput set-prop "pointer:Razer Razer DeathAdder Essential" "libinput Accel Profile Enabled" 0 1 0
xinput set-prop "pointer:Razer Razer DeathAdder Essential" "Coordinate Transformation Matrix" 0.6 0 0 0 0.6 0 0 0 1
xinput set-prop "SYNA32CF:00 06CB:CECD Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "SYNA32CF:00 06CB:CECD Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "SYNA32CF:00 06CB:CECD Touchpad" "libinput Accel Speed" 0.2

xcompmgr &
dwmblocks &
redshift -l 52.2424:16.5547 &
ssh-agent dwm
