#!/bin/sh

# defaults
xwallpaper --zoom ~/.config/x11/wallpaper.jpg
xset r rate 250 30
setxkbmap -option caps:escape pl
setdisps

# accel etc
xinput set-prop "pointer:Razer Razer DeathAdder Essential" "libinput Accel Profile Enabled" 0 1 0
xinput set-prop "SYNA32CF:00 06CB:CECD Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "SYNA32CF:00 06CB:CECD Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "SYNA32CF:00 06CB:CECD Touchpad" "libinput Accel Speed" "0.2"

xcompmgr &
dwmblocks &
ssh-agent dwm